version: "3.9"

services:
  polyflow-postgres:
    container_name: polyflow-postgres
    image: "postgres:13.4-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
